#!/usr/bin/env python3
"""Regenerate/check the notebook's deterministic embedded package from Python sources."""
import argparse
import ast
import base64
import hashlib
import io
import json
from pathlib import Path
import zipfile

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = ROOT / 'notebooks/Midterm_Sentiment_Agents_Colab.ipynb'


def source_files():
    files = [ROOT / p for p in ['README.md', 'pyproject.toml', 'AGENTS.md'] if (ROOT / p).is_file()]
    for folder in ['charisma_lab', 'data', 'docs', 'examples', 'tests']:
        files += [p for p in (ROOT / folder).rglob('*') if p.is_file() and
                  '__pycache__' not in p.parts and p.suffix in {'.py', '.csv', '.md', '.jsonl'}]
    files += [ROOT / 'reports/VALIDATION.md'] if (ROOT / 'reports/VALIDATION.md').is_file() else []
    # Workflow regression tests execute the embedded inline Python steps too.
    files += [p for p in (ROOT / '.github/workflows').glob('*.yml') if p.is_file()]
    return sorted(files)


def archive_bytes():
    out = io.BytesIO()
    with zipfile.ZipFile(out, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for path in source_files():
            info = zipfile.ZipInfo(path.relative_to(ROOT).as_posix(), date_time=(2026, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, path.read_bytes())
    return out.getvalue()


def bootstrap(payload):
    encoded = base64.b64encode(payload).decode()
    digest = hashlib.sha256(payload).hexdigest()
    return f'''# Generated by scripts/sync_notebook.py. Python source is authoritative.
import base64, hashlib, io, zipfile, sys, importlib.util, subprocess
from pathlib import Path
_EMBEDDED_SHA256 = {digest!r}
_EMBEDDED_PACKAGE = {encoded!r}
_payload = base64.b64decode(_EMBEDDED_PACKAGE, validate=True)
if hashlib.sha256(_payload).hexdigest() != _EMBEDDED_SHA256:
    raise ValueError("Embedded package integrity check failed")
PACKAGE = Path.cwd() / ("midterm_sentiment_code_" + _EMBEDDED_SHA256[:16])
for _name, _module in list(sys.modules.items()):
    if _name == "charisma_lab" or _name.startswith("charisma_lab."):
        _file = getattr(_module, "__file__", None)
        if not _file or not Path(_file).resolve().is_relative_to(PACKAGE.resolve()):
            raise RuntimeError("Another charisma_lab package is loaded. Restart the kernel before running this notebook.")
with zipfile.ZipFile(io.BytesIO(_payload)) as archive:
    base = PACKAGE.resolve()
    for item in archive.infolist():
        destination = (base / item.filename).resolve()
        if not destination.is_relative_to(base) or (item.external_attr >> 16) & 0o170000 == 0o120000:
            raise ValueError("Unsafe embedded archive path")
        if destination.exists() and destination.read_bytes() != archive.read(item):
            raise RuntimeError("Extracted source has local changes; preserve them and restart in a clean folder.")
    archive.extractall(PACKAGE)
if str(PACKAGE) not in sys.path:
    sys.path.insert(0, str(PACKAGE))
requirements = {{"requests":"requests>=2.31,<3", "numpy":"numpy>=1.26,<3",
                "pandas":"pandas>=2.1,<4", "defusedxml":"defusedxml>=0.7,<1", "yaml":"PyYAML>=6,<7"}}
missing = [requirement for module, requirement in requirements.items() if importlib.util.find_spec(module) is None]
if missing:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *missing])
print("Verified embedded Python package:", _EMBEDDED_SHA256, PACKAGE)
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    notebook = json.loads(NOTEBOOK.read_text())
    expected = bootstrap(archive_bytes())
    if args.check:
        if ''.join(notebook['cells'][1]['source']) != expected:
            raise SystemExit('Notebook is stale: run python scripts/sync_notebook.py')
        print('Notebook embedded package matches every selected source file.')
        return
    notebook['cells'][1]['source'] = expected.splitlines(keepends=True)
    for cell in notebook['cells']:
        if cell['cell_type'] == 'code':
            cell['outputs'] = []
            cell['execution_count'] = None
            ast.parse(''.join(cell['source']))
    NOTEBOOK.write_text(json.dumps(notebook, indent=1, ensure_ascii=False) + '\n')
    print('Regenerated', NOTEBOOK)


if __name__ == '__main__':
    main()
